import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import '@mantine/dates/styles.css';

import {ColorSchemeScript, MantineProvider} from '@mantine/core';
import Layout from "@/components/Layout";
import {ReactNode} from "react";
import {Notifications} from "@mantine/notifications";
import {ModalsProvider} from "@mantine/modals";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
        <head>
            <ColorSchemeScript/>
        </head>
        <body className={inter.className}>
        <MantineProvider>
            <Notifications/>
            <ModalsProvider>
                <Layout>{children}</Layout>
            </ModalsProvider>
        </MantineProvider>
        </body>
        </html>
    );
}
